### ISSUE TITLE
Email verification

### ISSUE THREAD

**Issue by OsePedro** [blackettlabfam/website#4]
We need to verify email addresses submitted through the sign-up form.
# Sub-Tasks

- [x] Initialise the `email-verified` value to “No”.
- [x] Append the row number, a timestamp and a secret key to their email address, and compute a MAC (message authentication code) of the result.
- [ ] Email them a link to the deployed Apps Script containing the following query string parameters:
  - `mode=verify-email`
  - `email=<email address>`
  - `row=<spreadsheet row>`
  - `ts=<timestamp>`
  - `mac=<digest>`
- [ ] When they click this link, `doGet` should recompute the MAC from the given parameters. If it doesn’t match the given MAC, it should terminate. 
  - This will allow the Apps Script to confirm that _it_ generated the given a query string, not a bot.
- [ ] `doGet` should then first check the given timestamp. If it doesn't lie within the past N hours, the script should reject the query.
  - This will allow us to change the secret key or MAC algorithm, if necessary. I.e. we’re free to change them when all timestamps in the spreadsheet are more than N hours old.
- [ ] Search for the row containing the email address, starting with the specified row. Searching will allow us to manually move rows.
- [ ] When the row is found, set its `email-verified` value to “Yes”.
